-- 사용자 테이블
CREATE TABLE TB_USERS (
    TB_USERS_UID VARCHAR(36) PRIMARY KEY COMMENT '사용자 고유 ID (UUID)',
    USERNAME VARCHAR(50) NOT NULL UNIQUE COMMENT '사용자 ID (로그인 ID)',
    PASSWORD_HASH VARCHAR(255) NOT NULL COMMENT '비밀번호 해시 (BCrypt)',
    CREATED_AT DATETIME NOT NULL COMMENT '생성 시간',
    UPDATED_AT DATETIME COMMENT '수정 시간',
    LAST_LOGIN_AT DATETIME COMMENT '마지막 로그인 시간',
    INDEX IDX_USER_USERNAME (USERNAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 사용자 API 키 테이블
CREATE TABLE TB_USER_API_KEYS (
    TB_USER_API_KEYS_UID VARCHAR(36) PRIMARY KEY COMMENT 'API 키 고유 ID (UUID)',
    USER_ID VARCHAR(36) NOT NULL COMMENT '사용자 ID (FK: TB_USERS.TB_USERS_UID)',
    BROKER_TYPE VARCHAR(50) NOT NULL COMMENT '증권사 타입 코드',
    APP_KEY_ENCRYPTED TEXT NOT NULL COMMENT 'App Key 암호화 값',
    APP_SECRET_ENCRYPTED TEXT NOT NULL COMMENT 'App Secret 암호화 값',
    SERVER_TYPE VARCHAR(1) NOT NULL DEFAULT '1' COMMENT '서버 타입 (1: 모의투자, 0: 실거래)',
    CREATED_AT DATETIME NOT NULL COMMENT '생성 시간',
    UPDATED_AT DATETIME COMMENT '수정 시간',
    INDEX IDX_USER_API_KEY_USER_ID (USER_ID),
    INDEX IDX_USER_API_KEY_BROKER_TYPE (BROKER_TYPE),
    FOREIGN KEY (USER_ID) REFERENCES TB_USERS(TB_USERS_UID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 사용자 계좌 테이블
CREATE TABLE TB_USER_ACCOUNTS (
    TB_USER_ACCOUNTS_UID VARCHAR(36) PRIMARY KEY COMMENT '계좌 고유 ID (UUID)',
    USER_ID VARCHAR(36) NOT NULL COMMENT '계좌 소유자 (FK: TB_USERS.TB_USERS_UID)',
    USER_API_KEY_ID VARCHAR(36) NOT NULL COMMENT '계좌에 사용할 API 키 (FK: TB_USER_API_KEYS)',
    ACCOUNT_NO_ENCRYPTED TEXT NOT NULL COMMENT '계좌번호 암호화 값',
    BROKER_TYPE VARCHAR(50) NOT NULL COMMENT '증권사 코드',
    SERVER_TYPE VARCHAR(1) NOT NULL DEFAULT '1' COMMENT '서버 타입 (1: 모의투자, 0: 실거래)',
    ACCOUNT_NAME VARCHAR(100) COMMENT '계좌 별칭 (표시용)',
    IS_DEFAULT TINYINT(1) NOT NULL DEFAULT 0 COMMENT '메인 계좌 여부 (서버타입별 1개)',
    IS_ACTIVE TINYINT(1) NOT NULL DEFAULT 1 COMMENT '활성화 여부',
    CREATED_AT DATETIME NOT NULL COMMENT '생성 시간',
    UPDATED_AT DATETIME COMMENT '수정 시간',
    INDEX IDX_USER_ACCOUNTS_USER_ID (USER_ID),
    INDEX IDX_USER_ACCOUNTS_USER_API_KEY (USER_API_KEY_ID),
    INDEX IDX_USER_ACCOUNTS_BROKER_TYPE (BROKER_TYPE),
    INDEX IDX_USER_ACCOUNTS_SERVER_TYPE (SERVER_TYPE),
    INDEX IDX_USER_ACCOUNTS_IS_DEFAULT (USER_ID, SERVER_TYPE, IS_DEFAULT),
    UNIQUE KEY UK_USER_ACCOUNTS_USER_ACCOUNT (USER_ID, ACCOUNT_NO_ENCRYPTED(255), BROKER_TYPE, SERVER_TYPE),
    FOREIGN KEY (USER_ID) REFERENCES TB_USERS(TB_USERS_UID) ON DELETE CASCADE,
    FOREIGN KEY (USER_API_KEY_ID) REFERENCES TB_USER_API_KEYS(TB_USER_API_KEYS_UID) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 주문 테이블
CREATE TABLE TB_ORDERS (
    TB_ORDERS_UID VARCHAR(36) PRIMARY KEY COMMENT '주문 고유 ID (UUID)',
    ACCOUNT_NO VARCHAR(20) NOT NULL COMMENT '계좌번호',
    USER_ID VARCHAR(36) COMMENT '사용자 ID (선택, 마이그레이션용)',
    SYMBOL VARCHAR(20) NOT NULL COMMENT '종목 코드',
    ORDER_TYPE VARCHAR(10) NOT NULL COMMENT '주문 유형 (BUY, SELL)',
    QUANTITY INT NOT NULL COMMENT '주문 수량',
    PRICE DECIMAL(18,2) NOT NULL COMMENT '주문 가격',
    STATUS VARCHAR(20) NOT NULL COMMENT '주문 상태',
    EXECUTED_QUANTITY INT COMMENT '체결 수량',
    EXECUTED_PRICE DECIMAL(18,2) COMMENT '체결 가격',
    ORDER_TIME DATETIME NOT NULL COMMENT '주문 시간',
    EXECUTED_TIME DATETIME COMMENT '체결 시간',
    MESSAGE VARCHAR(500) COMMENT '메시지',
    CREATED_AT DATETIME NOT NULL COMMENT '생성 시간',
    UPDATED_AT DATETIME COMMENT '수정 시간',
    INDEX IDX_TB_ORDERS_ACCOUNT_NO (ACCOUNT_NO),
    INDEX IDX_TB_ORDERS_USER_ID (USER_ID),
    INDEX IDX_TB_ORDERS_ORDER_TIME (ORDER_TIME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 거래 설정 테이블
CREATE TABLE TB_TRADING_SETTINGS (
    TB_TRADING_SETTINGS_UID VARCHAR(36) PRIMARY KEY COMMENT '설정 고유 ID (UUID)',
    ACCOUNT_NO VARCHAR(20) NOT NULL COMMENT '계좌번호',
    USER_ID VARCHAR(36) COMMENT '사용자 ID (설정 소유자)',
    MAX_INVESTMENT_AMOUNT DECIMAL(18,2) NOT NULL COMMENT '최대 투자금액',
    MIN_INVESTMENT_AMOUNT DECIMAL(18,2) NOT NULL COMMENT '최소 투자금액',
    DEFAULT_CURRENCY VARCHAR(3) NOT NULL COMMENT '기본 통화 (예: KRW)',
    AUTO_TRADING_ENABLED TINYINT(1) NOT NULL COMMENT '자동 매매 활성화 여부',
    RISK_LEVEL DECIMAL(3,2) COMMENT '리스크 레벨 (0.0~1.0)',
    CREATED_AT DATETIME NOT NULL COMMENT '생성 시간',
    UPDATED_AT DATETIME COMMENT '수정 시간',
    INDEX IDX_TB_TRADING_SETTINGS_ACCOUNT_NO (ACCOUNT_NO),
    INDEX IDX_TB_TRADING_SETTINGS_USER_ID (USER_ID),
    UNIQUE KEY UK_TB_TRADING_SETTINGS_USER_ACCOUNT (USER_ID, ACCOUNT_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 포트폴리오 테이블
CREATE TABLE TB_PORTFOLIOS (
    TB_PORTFOLIOS_UID VARCHAR(36) PRIMARY KEY COMMENT '포트폴리오 고유 ID (UUID)',
    ACCOUNT_NO VARCHAR(20) NOT NULL COMMENT '계좌번호',
    USER_ID VARCHAR(36) COMMENT '사용자 ID (선택, 마이그레이션용)',
    SYMBOL VARCHAR(20) NOT NULL COMMENT '종목 코드',
    NAME VARCHAR(100) COMMENT '종목명',
    QUANTITY INT NOT NULL COMMENT '보유 수량',
    AVERAGE_PRICE DECIMAL(18,2) NOT NULL COMMENT '평균 매수가',
    CURRENT_PRICE DECIMAL(18,2) COMMENT '현재가',
    CURRENCY VARCHAR(3) NOT NULL COMMENT '통화',
    LAST_UPDATED DATETIME COMMENT '마지막 업데이트 시간',
    CREATED_AT DATETIME NOT NULL COMMENT '생성 시간',
    UPDATED_AT DATETIME COMMENT '수정 시간',
    UNIQUE KEY UK_TB_PORTFOLIOS_ACCOUNT_SYMBOL (ACCOUNT_NO, SYMBOL),
    INDEX IDX_TB_PORTFOLIOS_ACCOUNT_NO (ACCOUNT_NO),
    INDEX IDX_TB_PORTFOLIOS_USER_ID (USER_ID),
    INDEX IDX_TB_PORTFOLIOS_SYMBOL (SYMBOL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 전략 테이블
CREATE TABLE TB_STRATEGIES (
    TB_STRATEGIES_UID VARCHAR(36) PRIMARY KEY COMMENT '전략 고유 ID (UUID)',
    ACCOUNT_NO VARCHAR(20) NOT NULL COMMENT '계좌번호',
    USER_ID VARCHAR(36) COMMENT '사용자 ID (선택, 마이그레이션용)',
    STRATEGY_TYPE VARCHAR(20) NOT NULL COMMENT '전략 타입',
    STATUS VARCHAR(20) NOT NULL COMMENT '전략 상태',
    MAX_INVESTMENT_AMOUNT DECIMAL(18,2) COMMENT '최대 투자금액',
    MIN_INVESTMENT_AMOUNT DECIMAL(18,2) COMMENT '최소 투자금액',
    RISK_LEVEL DECIMAL(3,2) COMMENT '리스크 레벨',
    CONFIDENCE_THRESHOLD DECIMAL(3,2) COMMENT '신뢰도 임계값',
    LAST_EXECUTED_AT DATETIME COMMENT '마지막 실행 시간',
    TOTAL_EXECUTIONS BIGINT DEFAULT 0 COMMENT '총 실행 횟수',
    SUCCESS_COUNT BIGINT DEFAULT 0 COMMENT '성공 횟수',
    FAILURE_COUNT BIGINT DEFAULT 0 COMMENT '실패 횟수',
    TOTAL_PROFIT_LOSS DECIMAL(18,2) DEFAULT 0 COMMENT '총 손익',
    CREATED_AT DATETIME NOT NULL COMMENT '생성 시간',
    UPDATED_AT DATETIME COMMENT '수정 시간',
    UNIQUE KEY UK_TB_STRATEGIES_ACCOUNT_TYPE (ACCOUNT_NO, STRATEGY_TYPE),
    UNIQUE KEY UK_TB_STRATEGIES_USER_ACCOUNT_TYPE (USER_ID, ACCOUNT_NO, STRATEGY_TYPE),
    INDEX IDX_TB_STRATEGIES_ACCOUNT_NO (ACCOUNT_NO),
    INDEX IDX_TB_STRATEGIES_USER_ID (USER_ID),
    INDEX IDX_TB_STRATEGIES_STATUS (STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 트레이딩 포트폴리오 테이블 (일별 트레이딩 계획)
CREATE TABLE TB_TRADING_PORTFOLIOS (
    TB_TRADING_PORTFOLIOS_UID VARCHAR(36) PRIMARY KEY COMMENT '포트폴리오 고유 ID (UUID)',
    TRADING_DATE DATE NOT NULL UNIQUE COMMENT '거래일',
    MARKET_SUMMARY TEXT COMMENT '시장 요약',
    TOP_SECTOR_1 VARCHAR(100) COMMENT '유망 섹터 1',
    TOP_SECTOR_2 VARCHAR(100) COMMENT '유망 섹터 2',
    TOP_SECTOR_3 VARCHAR(100) COMMENT '유망 섹터 3',
    RISK_MANAGEMENT_STRATEGY TEXT COMMENT '리스크 관리 전략',
    POSITION_SIZE DECIMAL(18,2) COMMENT '포지션 사이즈',
    CREATED_AT DATETIME NOT NULL COMMENT '생성 시간',
    UPDATED_AT DATETIME COMMENT '수정 시간',
    INDEX IDX_TB_TRADING_PORTFOLIOS_DATE (TRADING_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 트레이딩 포트폴리오 종목 테이블
CREATE TABLE TB_TRADING_PORTFOLIO_ITEMS (
    TB_TRADING_PORTFOLIO_ITEMS_UID VARCHAR(36) PRIMARY KEY COMMENT '종목 고유 ID (UUID)',
    TRADING_PORTFOLIO_ID VARCHAR(36) NOT NULL COMMENT '포트폴리오 ID (FK)',
    SYMBOL VARCHAR(20) NOT NULL COMMENT '종목 코드',
    NAME VARCHAR(100) COMMENT '종목명',
    ENTRY_PRICE_MIN DECIMAL(18,2) COMMENT '최소 진입가',
    ENTRY_PRICE_MAX DECIMAL(18,2) COMMENT '최대 진입가',
    STOP_LOSS_PRICE DECIMAL(18,2) COMMENT '손절가',
    TARGET_PRICE_1 DECIMAL(18,2) COMMENT '목표가 1',
    TARGET_PRICE_2 DECIMAL(18,2) COMMENT '목표가 2',
    EXPECTED_RETURN_RATE DECIMAL(5,2) COMMENT '기대 수익률 (%)',
    RISK_REWARD_RATIO DECIMAL(5,2) COMMENT '리스크/리워드 비율',
    TECHNICAL_BASIS TEXT COMMENT '기술적 근거',
    SUPPLY_DEMAND_BASIS TEXT COMMENT '수급 근거',
    CATALYST_FACTOR TEXT COMMENT '촉매 요인',
    BUY_TIME TIME NOT NULL COMMENT '매수 시간',
    SELL_TIME TIME COMMENT '매도 시간',
    INVESTMENT_AMOUNT DECIMAL(18,2) COMMENT '투자금액',
    EXPECTED_PROFIT DECIMAL(18,2) COMMENT '예상 수익',
    RANKING INT NOT NULL COMMENT '순위',
    CREATED_AT DATETIME NOT NULL COMMENT '생성 시간',
    UPDATED_AT DATETIME COMMENT '수정 시간',
    INDEX IDX_TB_TRADING_PORTFOLIO_ITEMS_PORTFOLIO (TRADING_PORTFOLIO_ID),
    INDEX IDX_TB_TRADING_PORTFOLIO_ITEMS_SYMBOL (SYMBOL),
    INDEX IDX_TB_TRADING_PORTFOLIO_ITEMS_RANKING (RANKING),
    FOREIGN KEY (TRADING_PORTFOLIO_ID) REFERENCES TB_TRADING_PORTFOLIOS(TB_TRADING_PORTFOLIOS_UID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
