-- 주문 테이블
CREATE TABLE TB_ORDERS (
    TB_ORDERS_UID VARCHAR(36) PRIMARY KEY,
    ACCOUNT_NO VARCHAR(20) NOT NULL,
    SYMBOL VARCHAR(20) NOT NULL,
    ORDER_TYPE VARCHAR(10) NOT NULL,
    QUANTITY INT NOT NULL,
    PRICE DECIMAL(18,2) NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    EXECUTED_QUANTITY INT,
    EXECUTED_PRICE DECIMAL(18,2),
    ORDER_TIME DATETIME NOT NULL,
    EXECUTED_TIME DATETIME,
    MESSAGE VARCHAR(500),
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME,
    INDEX IDX_TB_ORDERS_ACCOUNT_NO (ACCOUNT_NO),
    INDEX IDX_TB_ORDERS_ORDER_TIME (ORDER_TIME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 거래 설정 테이블
CREATE TABLE TB_TRADING_SETTINGS (
    TB_TRADING_SETTINGS_UID VARCHAR(36) PRIMARY KEY,
    ACCOUNT_NO VARCHAR(20) NOT NULL UNIQUE,
    MAX_INVESTMENT_AMOUNT DECIMAL(18,2) NOT NULL,
    MIN_INVESTMENT_AMOUNT DECIMAL(18,2) NOT NULL,
    DEFAULT_CURRENCY VARCHAR(3) NOT NULL,
    AUTO_TRADING_ENABLED TINYINT(1) NOT NULL,
    RISK_LEVEL DECIMAL(3,2),
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME,
    INDEX IDX_TB_TRADING_SETTINGS_ACCOUNT_NO (ACCOUNT_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 포트폴리오 테이블
CREATE TABLE TB_PORTFOLIOS (
    TB_PORTFOLIOS_UID VARCHAR(36) PRIMARY KEY,
    ACCOUNT_NO VARCHAR(20) NOT NULL,
    SYMBOL VARCHAR(20) NOT NULL,
    NAME VARCHAR(100),
    QUANTITY INT NOT NULL,
    AVERAGE_PRICE DECIMAL(18,2) NOT NULL,
    CURRENT_PRICE DECIMAL(18,2),
    CURRENCY VARCHAR(3) NOT NULL,
    LAST_UPDATED DATETIME,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME,
    UNIQUE KEY UK_TB_PORTFOLIOS_ACCOUNT_SYMBOL (ACCOUNT_NO, SYMBOL),
    INDEX IDX_TB_PORTFOLIOS_ACCOUNT_NO (ACCOUNT_NO),
    INDEX IDX_TB_PORTFOLIOS_SYMBOL (SYMBOL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 전략 테이블
CREATE TABLE TB_STRATEGIES (
    TB_STRATEGIES_UID VARCHAR(36) PRIMARY KEY,
    ACCOUNT_NO VARCHAR(20) NOT NULL,
    STRATEGY_TYPE VARCHAR(20) NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    MAX_INVESTMENT_AMOUNT DECIMAL(18,2),
    MIN_INVESTMENT_AMOUNT DECIMAL(18,2),
    RISK_LEVEL DECIMAL(3,2),
    CONFIDENCE_THRESHOLD DECIMAL(3,2),
    LAST_EXECUTED_AT DATETIME,
    TOTAL_EXECUTIONS BIGINT DEFAULT 0,
    SUCCESS_COUNT BIGINT DEFAULT 0,
    FAILURE_COUNT BIGINT DEFAULT 0,
    TOTAL_PROFIT_LOSS DECIMAL(18,2) DEFAULT 0,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME,
    UNIQUE KEY UK_TB_STRATEGIES_ACCOUNT_TYPE (ACCOUNT_NO, STRATEGY_TYPE),
    INDEX IDX_TB_STRATEGIES_ACCOUNT_NO (ACCOUNT_NO),
    INDEX IDX_TB_STRATEGIES_STATUS (STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 트레이딩 포트폴리오 테이블 (일별 트레이딩 계획)
CREATE TABLE TB_TRADING_PORTFOLIOS (
    TB_TRADING_PORTFOLIOS_UID VARCHAR(36) PRIMARY KEY,
    TRADING_DATE DATE NOT NULL UNIQUE,
    MARKET_SUMMARY TEXT,
    TOP_SECTOR_1 VARCHAR(100),
    TOP_SECTOR_2 VARCHAR(100),
    TOP_SECTOR_3 VARCHAR(100),
    RISK_MANAGEMENT_STRATEGY TEXT,
    POSITION_SIZE DECIMAL(18,2),
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME,
    INDEX IDX_TB_TRADING_PORTFOLIOS_DATE (TRADING_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 트레이딩 포트폴리오 종목 테이블
CREATE TABLE TB_TRADING_PORTFOLIO_ITEMS (
    TB_TRADING_PORTFOLIO_ITEMS_UID VARCHAR(36) PRIMARY KEY,
    TRADING_PORTFOLIO_ID VARCHAR(36) NOT NULL,
    SYMBOL VARCHAR(20) NOT NULL,
    NAME VARCHAR(100),
    ENTRY_PRICE_MIN DECIMAL(18,2),
    ENTRY_PRICE_MAX DECIMAL(18,2),
    STOP_LOSS_PRICE DECIMAL(18,2),
    TARGET_PRICE_1 DECIMAL(18,2),
    TARGET_PRICE_2 DECIMAL(18,2),
    EXPECTED_RETURN_RATE DECIMAL(5,2),
    RISK_REWARD_RATIO DECIMAL(5,2),
    TECHNICAL_BASIS TEXT,
    SUPPLY_DEMAND_BASIS TEXT,
    CATALYST_FACTOR TEXT,
    BUY_TIME TIME NOT NULL,
    SELL_TIME TIME,
    INVESTMENT_AMOUNT DECIMAL(18,2),
    EXPECTED_PROFIT DECIMAL(18,2),
    RANKING INT NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME,
    INDEX IDX_TB_TRADING_PORTFOLIO_ITEMS_PORTFOLIO (TRADING_PORTFOLIO_ID),
    INDEX IDX_TB_TRADING_PORTFOLIO_ITEMS_SYMBOL (SYMBOL),
    INDEX IDX_TB_TRADING_PORTFOLIO_ITEMS_RANKING (RANKING),
    FOREIGN KEY (TRADING_PORTFOLIO_ID) REFERENCES TB_TRADING_PORTFOLIOS(TB_TRADING_PORTFOLIOS_UID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
