-- V12 롤백: TB_KOREA_INVESTMENT_TOKENS SERVER_TYPE 컬럼 및 UK 제거
-- 실행 전 DB 백업 권장.
-- 주의: SERVER_TYPE별로 2건 이상 저장된 사용자는 롤백 후 1건만 남기고 정리 필요.

ALTER TABLE TB_KOREA_INVESTMENT_TOKENS
    DROP INDEX UK_KI_TOKENS_USER_SERVER;

ALTER TABLE TB_KOREA_INVESTMENT_TOKENS
    DROP COLUMN SERVER_TYPE;
