-- V3 롤백: TB_NEWS_ITEMS 제거, TB_STRATEGIES에서 MARKET 제거 및 V3에서 추가한 인덱스 제거
-- 실행 전 DB 백업 권장. 적용 후 기존 UK(ACCOUNT_NO, STRATEGY_TYPE)가 필요하면 수동으로 재생성.

-- 1. TB_NEWS_ITEMS 테이블 삭제
DROP TABLE IF EXISTS TB_NEWS_ITEMS;

-- 2. TB_STRATEGIES: V3에서 추가한 UNIQUE/INDEX 제거 후 MARKET 컬럼 제거
ALTER TABLE TB_STRATEGIES DROP INDEX UK_TB_STRATEGIES_ACCOUNT_MARKET_TYPE;
ALTER TABLE TB_STRATEGIES DROP INDEX IDX_TB_STRATEGIES_MARKET;
ALTER TABLE TB_STRATEGIES DROP COLUMN MARKET;

-- (선택) 기존 UK 복원이 필요하면 수동 실행:
-- ALTER TABLE TB_STRATEGIES ADD UNIQUE INDEX UK_TB_STRATEGIES_ACCOUNT_TYPE (ACCOUNT_NO, STRATEGY_TYPE);
-- ALTER TABLE TB_STRATEGIES ADD UNIQUE INDEX UK_TB_STRATEGIES_USER_ACCOUNT_TYPE (USER_ID, ACCOUNT_NO, STRATEGY_TYPE);
