-- V8 롤백: TB_STRATEGY_POSITION에서 STRATEGY_TYPE 관련 컬럼·인덱스 제거
-- 실행 전 DB 백업 권장.

DROP INDEX IF EXISTS IDX_TB_STRATEGY_POSITION_ACCOUNT_EXIT_TYPE ON TB_STRATEGY_POSITION;
ALTER TABLE TB_STRATEGY_POSITION DROP COLUMN STRATEGY_TYPE;
