-- V10: TB_TRADING_SETTINGS에 단기/중기/장기 비율 컬럼 추가
-- 적용 전 DB 백업 권장. 롤백: db/migration/rollback/V10_rollback.sql 참고.
-- 비율은 0~1, 합=1. NULL이면 스케줄러에서 기본값 0.2/0.4/0.4 사용.

ALTER TABLE TB_TRADING_SETTINGS
    ADD COLUMN SHORT_TERM_RATIO DECIMAL(5,4) NULL COMMENT '단기 비율 (0~1, NULL이면 기본 0.2)' AFTER RISK_LEVEL,
    ADD COLUMN MEDIUM_TERM_RATIO DECIMAL(5,4) NULL COMMENT '중기 비율 (0~1, NULL이면 기본 0.4)' AFTER SHORT_TERM_RATIO,
    ADD COLUMN LONG_TERM_RATIO DECIMAL(5,4) NULL COMMENT '장기 비율 (0~1, NULL이면 기본 0.4)' AFTER MEDIUM_TERM_RATIO;
