-- V13: Sector Relative Strength(한국) 유니버스 필터용 테이블
-- 적용 전 DB 백업 권장. 롤백: db/migration/rollback/V13_rollback.sql 참고.

-- 업종별 수익률 (기준일·시장별)
CREATE TABLE IF NOT EXISTS TB_SECTOR_RETURN (
    BAS_DT DATE NOT NULL COMMENT '기준일자',
    MARKET VARCHAR(10) NOT NULL DEFAULT 'KR' COMMENT '시장 (KR, US)',
    SECTOR_CODE VARCHAR(50) NOT NULL COMMENT '업종/섹터 코드',
    RETURN_PCT DECIMAL(12, 4) NULL COMMENT '기간 수익률 (%)',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 시간',
    PRIMARY KEY (BAS_DT, MARKET, SECTOR_CODE),
    INDEX IDX_TB_SECTOR_RETURN_BAS_DT_MARKET (BAS_DT, MARKET)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='업종별 수익률(Sector RS 필터용)';

-- 종목-업종 매핑
CREATE TABLE IF NOT EXISTS TB_SYMBOL_SECTOR (
    SYMBOL VARCHAR(20) NOT NULL COMMENT '종목코드',
    MARKET VARCHAR(10) NOT NULL DEFAULT 'KR' COMMENT '시장',
    SECTOR_CODE VARCHAR(50) NOT NULL COMMENT '업종/섹터 코드',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 시간',
    PRIMARY KEY (SYMBOL, MARKET, SECTOR_CODE),
    INDEX IDX_TB_SYMBOL_SECTOR_MARKET_SECTOR (MARKET, SECTOR_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='종목-업종 매핑(Sector RS 필터용)';
