-- V14: Post-Earnings Drift(미국) 유니버스 필터용 테이블
-- 적용 전 DB 백업 권장. 롤백: db/migration/rollback/V14_rollback.sql 참고.

CREATE TABLE IF NOT EXISTS TB_EARNINGS_SURPRISE (
    SYMBOL VARCHAR(20) NOT NULL COMMENT '종목코드',
    MARKET VARCHAR(10) NOT NULL DEFAULT 'US' COMMENT '시장',
    REPORT_DT DATE NOT NULL COMMENT '실적 발표일',
    SURPRISE_SCORE DECIMAL(12, 4) NULL COMMENT '어닝 서프라이즈 강도 (실적 vs 컨센서스)',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 시간',
    PRIMARY KEY (SYMBOL, MARKET, REPORT_DT),
    INDEX IDX_TB_EARNINGS_SURPRISE_MARKET_REPORT_DT (MARKET, REPORT_DT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='어닝 서프라이즈(Post-Earnings Drift 필터용)';
