-- V15: 수급 강도(한국 Smart Money Intensity) 시그널용 테이블
-- 적용 전 DB 백업 권장. 롤백: db/migration/rollback/V15_rollback.sql 참고.

CREATE TABLE IF NOT EXISTS TB_ORDER_FLOW (
    BAS_DT DATE NOT NULL COMMENT '기준일자',
    SYMBOL VARCHAR(20) NOT NULL COMMENT '종목코드',
    MARKET VARCHAR(10) NOT NULL DEFAULT 'KR' COMMENT '시장',
    NET_BUY_AMT_5D BIGINT NULL COMMENT '최근 5일 누적 순매수 금액 (원)',
    MARKET_CAP BIGINT NULL COMMENT '시가총액 (원)',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 시간',
    PRIMARY KEY (BAS_DT, SYMBOL, MARKET),
    INDEX IDX_TB_ORDER_FLOW_BAS_DT_MARKET (BAS_DT, MARKET)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='수급 데이터(Smart Money Intensity 시그널용)';
