-- V16: 퀄리티-성장(미국 PEG & Rule of 40) 시그널용 테이블
-- 적용 전 DB 백업 권장. 롤백: db/migration/rollback/V16_rollback.sql 참고.

CREATE TABLE IF NOT EXISTS TB_FUNDAMENTALS (
    BAS_DT DATE NOT NULL COMMENT '기준일자',
    SYMBOL VARCHAR(20) NOT NULL COMMENT '종목코드',
    MARKET VARCHAR(10) NOT NULL DEFAULT 'US' COMMENT '시장',
    PER DECIMAL(12, 4) NULL COMMENT 'PER',
    PEG DECIMAL(12, 4) NULL COMMENT 'PEG (PER / EPS 성장률)',
    REVENUE_GROWTH_PCT DECIMAL(12, 4) NULL COMMENT '매출증가율 (%)',
    OPERATING_MARGIN_PCT DECIMAL(12, 4) NULL COMMENT '영업이익률 (%)',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 시간',
    PRIMARY KEY (BAS_DT, SYMBOL, MARKET),
    INDEX IDX_TB_FUNDAMENTALS_BAS_DT_MARKET (BAS_DT, MARKET)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='재무 데이터(PEG & Rule of 40 시그널용)';
