-- TB_USER_ACCOUNTS에 SERVER_TYPE 컬럼 추가 (모의/실거래 계좌 구분)
-- 실행 전 백업 권장. 롤백: 컬럼 삭제 및 기존 UK 복구

-- 1. SERVER_TYPE 컬럼 추가 (기본값 모의투자)
ALTER TABLE TB_USER_ACCOUNTS
    ADD COLUMN SERVER_TYPE VARCHAR(1) NOT NULL DEFAULT '1'
    COMMENT '서버 타입 (1: 모의투자, 0: 실거래)'
    AFTER BROKER_TYPE;

-- 2. 기존 데이터 보정: 연결된 UserApiKey의 SERVER_TYPE으로 채움
UPDATE TB_USER_ACCOUNTS ua
JOIN TB_USER_API_KEYS uk ON ua.USER_API_KEY_ID = uk.TB_USER_API_KEYS_UID
SET ua.SERVER_TYPE = uk.SERVER_TYPE
WHERE ua.SERVER_TYPE = '1' OR ua.SERVER_TYPE IS NULL;

-- 3. 기존 UNIQUE 제약 삭제
ALTER TABLE TB_USER_ACCOUNTS
    DROP INDEX UK_USER_ACCOUNTS_USER_ACCOUNT;

-- 4. 새 UNIQUE 제약 (USER_ID, ACCOUNT_NO_ENCRYPTED, BROKER_TYPE, SERVER_TYPE)
ALTER TABLE TB_USER_ACCOUNTS
    ADD UNIQUE KEY UK_USER_ACCOUNTS_USER_ACCOUNT (USER_ID, ACCOUNT_NO_ENCRYPTED(255), BROKER_TYPE, SERVER_TYPE);

-- 5. 인덱스 추가
ALTER TABLE TB_USER_ACCOUNTS
    ADD INDEX IDX_USER_ACCOUNTS_SERVER_TYPE (SERVER_TYPE);

-- 6. 기존 복합 인덱스 삭제 후 서버 타입 포함하여 재생성
-- IDX_USER_ACCOUNTS_IS_DEFAULT: (USER_ID, IS_DEFAULT) -> (USER_ID, SERVER_TYPE, IS_DEFAULT)
DROP INDEX IF EXISTS IDX_USER_ACCOUNTS_IS_DEFAULT ON TB_USER_ACCOUNTS;
ALTER TABLE TB_USER_ACCOUNTS
    ADD INDEX IDX_USER_ACCOUNTS_IS_DEFAULT (USER_ID, SERVER_TYPE, IS_DEFAULT);
