-- Spring Batch 5 expects SEQUENCE objects (PostgreSQL native).
-- V21 created tables with the same names (BATCH_*_SEQ); drop those first, then create real sequences.

DROP TABLE IF EXISTS BATCH_STEP_EXECUTION_SEQ;
DROP TABLE IF EXISTS BATCH_JOB_EXECUTION_SEQ;
DROP TABLE IF EXISTS BATCH_JOB_INSTANCE_SEQ;

DROP SEQUENCE IF EXISTS BATCH_JOB_SEQ;
CREATE SEQUENCE BATCH_JOB_SEQ
    START WITH 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    CACHE 1
    NO CYCLE;

DROP SEQUENCE IF EXISTS BATCH_JOB_EXECUTION_SEQ;
CREATE SEQUENCE BATCH_JOB_EXECUTION_SEQ
    START WITH 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    CACHE 1
    NO CYCLE;

DROP SEQUENCE IF EXISTS BATCH_STEP_EXECUTION_SEQ;
CREATE SEQUENCE BATCH_STEP_EXECUTION_SEQ
    START WITH 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    CACHE 1
    NO CYCLE;
