-- Spring Batch 5 expects SEQUENCE objects on MariaDB 10.3+ (not only *_SEQ tables).
-- Names: BATCH_JOB_SEQ, BATCH_JOB_EXECUTION_SEQ, BATCH_STEP_EXECUTION_SEQ.
-- Ref: Spring Batch 5.0 Migration Guide. MariaDB: MINVALUE default 1, MAXVALUE <= 9223372036854775806 (LONGLONG_MAX-1).
-- DROP first so a previously failed run (wrong options) is replaced.

DROP SEQUENCE IF EXISTS BATCH_JOB_SEQ;
CREATE SEQUENCE IF NOT EXISTS BATCH_JOB_SEQ
    START WITH 1
    MINVALUE 1
    MAXVALUE 9223372036854775806
    NOCACHE
    NOCYCLE;

DROP SEQUENCE IF EXISTS BATCH_JOB_EXECUTION_SEQ;
CREATE SEQUENCE IF NOT EXISTS BATCH_JOB_EXECUTION_SEQ
    START WITH 1
    MINVALUE 1
    MAXVALUE 9223372036854775806
    NOCACHE
    NOCYCLE;

DROP SEQUENCE IF EXISTS BATCH_STEP_EXECUTION_SEQ;
CREATE SEQUENCE IF NOT EXISTS BATCH_STEP_EXECUTION_SEQ
    START WITH 1
    MINVALUE 1
    MAXVALUE 9223372036854775806
    NOCACHE
    NOCYCLE;
