-- V21 created tables BATCH_*_SEQ for sequence emulation; V22 created real SEQUENCEs.
-- When both exist, Spring Batch 5 resolves the name to the table and fails with "is not a SEQUENCE".
-- Drop the old tables so only the SEQUENCE objects are used; then ensure sequences exist.

DROP TABLE IF EXISTS BATCH_STEP_EXECUTION_SEQ;
DROP TABLE IF EXISTS BATCH_JOB_EXECUTION_SEQ;
DROP TABLE IF EXISTS BATCH_JOB_INSTANCE_SEQ;

CREATE SEQUENCE IF NOT EXISTS BATCH_JOB_SEQ
    START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775806 NOCACHE NOCYCLE;
CREATE SEQUENCE IF NOT EXISTS BATCH_JOB_EXECUTION_SEQ
    START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775806 NOCACHE NOCYCLE;
CREATE SEQUENCE IF NOT EXISTS BATCH_STEP_EXECUTION_SEQ
    START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775806 NOCACHE NOCYCLE;
