-- Phase 2: Kill Switch (전체 주문 차단) 및 MDD 계산용 포트폴리오 피크.
-- TB_TRADING_HALT: 단일 행(id=1). halt_all_orders=true 시 모든 주문 차단.
-- TB_PORTFOLIO_PEAK: 계좌별 누적 최고 평가액. MDD = (peak - current) / peak 계산용.

CREATE TABLE IF NOT EXISTS TB_TRADING_HALT (
    ID INTEGER PRIMARY KEY DEFAULT 1,
    HALT_ALL_ORDERS BOOLEAN NOT NULL DEFAULT FALSE,
    UPDATED_AT TIMESTAMP
);

COMMENT ON TABLE TB_TRADING_HALT IS '긴급 시 전체 주문 차단(Kill Switch). 단일 행(id=1)';
COMMENT ON COLUMN TB_TRADING_HALT.HALT_ALL_ORDERS IS 'true=모든 주문 차단';

INSERT INTO TB_TRADING_HALT (ID, HALT_ALL_ORDERS, UPDATED_AT)
VALUES (1, FALSE, CURRENT_TIMESTAMP)
ON CONFLICT (ID) DO NOTHING;

CREATE TABLE IF NOT EXISTS TB_PORTFOLIO_PEAK (
    ACCOUNT_NO VARCHAR(20) NOT NULL PRIMARY KEY,
    PEAK_VALUE NUMERIC(18,2) NOT NULL,
    PEAK_DATE DATE NOT NULL,
    UPDATED_AT TIMESTAMP
);

COMMENT ON TABLE TB_PORTFOLIO_PEAK IS '계좌별 평가액 피크. PreTradeCompliance MDD(15%) 검사용';
