-- Ops 알림센터: 긴급/시스템 알림 이력 (Discord 발송 시 동일 내용 저장).
CREATE TABLE IF NOT EXISTS TB_ALERT_LOG (
    ID BIGSERIAL PRIMARY KEY,
    OCCURRED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LEVEL VARCHAR(20) NOT NULL,
    COMPONENT VARCHAR(100),
    MESSAGE TEXT
);

CREATE INDEX IF NOT EXISTS IDX_TB_ALERT_LOG_OCCURRED_AT ON TB_ALERT_LOG (OCCURRED_AT DESC);
CREATE INDEX IF NOT EXISTS IDX_TB_ALERT_LOG_LEVEL ON TB_ALERT_LOG (LEVEL);

COMMENT ON TABLE TB_ALERT_LOG IS 'Ops 알림센터: Discord 등 발송 알림 이력';
COMMENT ON COLUMN TB_ALERT_LOG.LEVEL IS 'INFO, WARNING, ERROR';
COMMENT ON COLUMN TB_ALERT_LOG.COMPONENT IS '발신 컴포넌트(예: UnfilledOrder, RiskGate, Execution)';
