-- Ops 감사 로그: 설정 변경·수동 트리거·실계좌 가드 차단 이벤트 (사용자·계좌 마스킹 저장).
CREATE TABLE IF NOT EXISTS TB_AUDIT_LOG (
    ID BIGSERIAL PRIMARY KEY,
    OCCURRED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    EVENT_TYPE VARCHAR(64) NOT NULL,
    USER_ID_MASKED VARCHAR(64),
    ACCOUNT_NO_MASKED VARCHAR(32),
    SUMMARY VARCHAR(500),
    RESULT VARCHAR(32),
    IP_ADDRESS VARCHAR(64),
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS IDX_TB_AUDIT_LOG_OCCURRED_AT ON TB_AUDIT_LOG (OCCURRED_AT DESC);
CREATE INDEX IF NOT EXISTS IDX_TB_AUDIT_LOG_EVENT_TYPE ON TB_AUDIT_LOG (EVENT_TYPE);

COMMENT ON TABLE TB_AUDIT_LOG IS 'Ops 감사 로그: 설정 변경·수동 트리거·실계좌 가드 차단 등';
COMMENT ON COLUMN TB_AUDIT_LOG.EVENT_TYPE IS 'SETTING_CHANGE, MANUAL_TRIGGER, REAL_ACCOUNT_GUARD_BLOCKED 등';
COMMENT ON COLUMN TB_AUDIT_LOG.USER_ID_MASKED IS '마스킹된 사용자 ID';
COMMENT ON COLUMN TB_AUDIT_LOG.ACCOUNT_NO_MASKED IS '마스킹된 계좌번호';
COMMENT ON COLUMN TB_AUDIT_LOG.RESULT IS 'SUCCESS, FAILURE 등';
