-- Create TB_ORDERS and TB_STRATEGY_POSITION so V30 (trade_reason_columns) can ALTER them.
-- Schema matches Order and StrategyPosition entities; V30 adds SIGNAL_TYPE, EXIT_RULE_TYPE.

CREATE TABLE IF NOT EXISTS TB_ORDERS (
    TB_ORDERS_UID         VARCHAR(36) NOT NULL PRIMARY KEY,
    ACCOUNT_NO            VARCHAR(20) NOT NULL,
    USER_ID               VARCHAR(36),
    SYMBOL                VARCHAR(20) NOT NULL,
    ORDER_TYPE            VARCHAR(10) NOT NULL,
    QUANTITY              INTEGER NOT NULL,
    PRICE                 NUMERIC(18,2) NOT NULL,
    STATUS                VARCHAR(20) NOT NULL,
    EXECUTED_QUANTITY     INTEGER,
    EXECUTED_PRICE        NUMERIC(18,2),
    ORDER_TIME            TIMESTAMP(6) NOT NULL,
    EXECUTED_TIME         TIMESTAMP(6),
    MESSAGE               VARCHAR(500),
    POSITION_BAS_DT       DATE,
    POSITION_MARKET       VARCHAR(10),
    POSITION_STRATEGY_TYPE VARCHAR(20),
    CREATED_AT            TIMESTAMP(6) NOT NULL,
    UPDATED_AT            TIMESTAMP(6)
);

CREATE INDEX IF NOT EXISTS IDX_TB_ORDERS_USER_ID ON TB_ORDERS (USER_ID);

CREATE TABLE IF NOT EXISTS TB_STRATEGY_POSITION (
    ID                BIGSERIAL PRIMARY KEY,
    ACCOUNT_NO        VARCHAR(20) NOT NULL,
    SYMBOL            VARCHAR(20) NOT NULL,
    MARKET            VARCHAR(10) NOT NULL,
    STRATEGY_TYPE     VARCHAR(20) NOT NULL,
    ENTRY_DT          DATE NOT NULL,
    ENTRY_PRICE       NUMERIC(20,4) NOT NULL,
    QUANTITY          INTEGER NOT NULL,
    TRAILING_HIGH     NUMERIC(20,4),
    PRIOR_LOW         NUMERIC(20,4),
    ATR_MULTIPLIER    NUMERIC(10,4) NOT NULL DEFAULT 2.0,
    TIME_CUT_DAYS     INTEGER NOT NULL,
    TARGET_RETURN_PCT NUMERIC(10,4),
    CREATED_AT        TIMESTAMP(6) NOT NULL,
    EXIT_DT           DATE,
    EXIT_PRICE        NUMERIC(20,4)
);

CREATE INDEX IF NOT EXISTS IDX_TB_STRATEGY_POSITION_ACCOUNT ON TB_STRATEGY_POSITION (ACCOUNT_NO);
CREATE INDEX IF NOT EXISTS IDX_TB_STRATEGY_POSITION_SYMBOL ON TB_STRATEGY_POSITION (SYMBOL);
CREATE INDEX IF NOT EXISTS IDX_TB_STRATEGY_POSITION_OPEN ON TB_STRATEGY_POSITION (ACCOUNT_NO, EXIT_DT);
CREATE INDEX IF NOT EXISTS IDX_TB_STRATEGY_POSITION_ACCOUNT_EXIT_TYPE ON TB_STRATEGY_POSITION (ACCOUNT_NO, EXIT_DT, STRATEGY_TYPE);
