-- 모든 테이블 컬럼에 COMMENT 추가
-- 실행 전 백업 권장. 롤백 시 COMMENT 제거하려면 동일 컬럼을 COMMENT '' 로 MODIFY

-- TB_USERS
ALTER TABLE TB_USERS MODIFY COLUMN TB_USERS_UID VARCHAR(36) COMMENT '사용자 고유 ID (UUID)';
ALTER TABLE TB_USERS MODIFY COLUMN USERNAME VARCHAR(50) COMMENT '사용자 ID (로그인 ID)';
ALTER TABLE TB_USERS MODIFY COLUMN PASSWORD_HASH VARCHAR(255) COMMENT '비밀번호 해시 (BCrypt)';
ALTER TABLE TB_USERS MODIFY COLUMN CREATED_AT DATETIME COMMENT '생성 시간';
ALTER TABLE TB_USERS MODIFY COLUMN UPDATED_AT DATETIME COMMENT '수정 시간';
ALTER TABLE TB_USERS MODIFY COLUMN LAST_LOGIN_AT DATETIME COMMENT '마지막 로그인 시간';

-- TB_USER_API_KEYS
ALTER TABLE TB_USER_API_KEYS MODIFY COLUMN TB_USER_API_KEYS_UID VARCHAR(36) COMMENT 'API 키 고유 ID (UUID)';
ALTER TABLE TB_USER_API_KEYS MODIFY COLUMN USER_ID VARCHAR(36) COMMENT '사용자 ID (FK: TB_USERS.TB_USERS_UID)';
ALTER TABLE TB_USER_API_KEYS MODIFY COLUMN BROKER_TYPE VARCHAR(50) COMMENT '증권사 타입 코드 (예: KOREA_INVESTMENT)';
ALTER TABLE TB_USER_API_KEYS MODIFY COLUMN APP_KEY_ENCRYPTED TEXT COMMENT 'App Key 암호화 값';
ALTER TABLE TB_USER_API_KEYS MODIFY COLUMN APP_SECRET_ENCRYPTED TEXT COMMENT 'App Secret 암호화 값';
ALTER TABLE TB_USER_API_KEYS MODIFY COLUMN SERVER_TYPE VARCHAR(1) COMMENT '서버 타입 (1: 모의투자, 0: 실거래)';
ALTER TABLE TB_USER_API_KEYS MODIFY COLUMN CREATED_AT DATETIME COMMENT '생성 시간';
ALTER TABLE TB_USER_API_KEYS MODIFY COLUMN UPDATED_AT DATETIME COMMENT '수정 시간';

-- TB_USER_ACCOUNTS
ALTER TABLE TB_USER_ACCOUNTS MODIFY COLUMN TB_USER_ACCOUNTS_UID VARCHAR(36) COMMENT '계좌 고유 ID (UUID)';
ALTER TABLE TB_USER_ACCOUNTS MODIFY COLUMN USER_ID VARCHAR(36) COMMENT '계좌 소유자 (FK: TB_USERS.TB_USERS_UID)';
ALTER TABLE TB_USER_ACCOUNTS MODIFY COLUMN USER_API_KEY_ID VARCHAR(36) COMMENT '계좌에 사용할 API 키 (FK: TB_USER_API_KEYS)';
ALTER TABLE TB_USER_ACCOUNTS MODIFY COLUMN ACCOUNT_NO_ENCRYPTED TEXT COMMENT '계좌번호 암호화 값';
ALTER TABLE TB_USER_ACCOUNTS MODIFY COLUMN BROKER_TYPE VARCHAR(50) COMMENT '증권사 코드';
ALTER TABLE TB_USER_ACCOUNTS MODIFY COLUMN SERVER_TYPE VARCHAR(1) COMMENT '서버 타입 (1: 모의투자, 0: 실거래)';
ALTER TABLE TB_USER_ACCOUNTS MODIFY COLUMN ACCOUNT_NAME VARCHAR(100) COMMENT '계좌 별칭 (표시용)';
ALTER TABLE TB_USER_ACCOUNTS MODIFY COLUMN IS_DEFAULT TINYINT(1) COMMENT '메인 계좌 여부 (사용자당 서버타입별 1개)';
ALTER TABLE TB_USER_ACCOUNTS MODIFY COLUMN IS_ACTIVE TINYINT(1) COMMENT '활성화 여부';
ALTER TABLE TB_USER_ACCOUNTS MODIFY COLUMN CREATED_AT DATETIME COMMENT '생성 시간';
ALTER TABLE TB_USER_ACCOUNTS MODIFY COLUMN UPDATED_AT DATETIME COMMENT '수정 시간';

-- TB_ORDERS
ALTER TABLE TB_ORDERS MODIFY COLUMN TB_ORDERS_UID VARCHAR(36) COMMENT '주문 고유 ID (UUID)';
ALTER TABLE TB_ORDERS MODIFY COLUMN ACCOUNT_NO VARCHAR(20) COMMENT '계좌번호';
ALTER TABLE TB_ORDERS MODIFY COLUMN USER_ID VARCHAR(36) COMMENT '사용자 ID (선택, 마이그레이션용)';
ALTER TABLE TB_ORDERS MODIFY COLUMN SYMBOL VARCHAR(20) COMMENT '종목 코드';
ALTER TABLE TB_ORDERS MODIFY COLUMN ORDER_TYPE VARCHAR(10) COMMENT '주문 유형 (BUY, SELL)';
ALTER TABLE TB_ORDERS MODIFY COLUMN QUANTITY INT COMMENT '주문 수량';
ALTER TABLE TB_ORDERS MODIFY COLUMN PRICE DECIMAL(18,2) COMMENT '주문 가격';
ALTER TABLE TB_ORDERS MODIFY COLUMN STATUS VARCHAR(20) COMMENT '주문 상태';
ALTER TABLE TB_ORDERS MODIFY COLUMN EXECUTED_QUANTITY INT COMMENT '체결 수량';
ALTER TABLE TB_ORDERS MODIFY COLUMN EXECUTED_PRICE DECIMAL(18,2) COMMENT '체결 가격';
ALTER TABLE TB_ORDERS MODIFY COLUMN ORDER_TIME DATETIME COMMENT '주문 시간';
ALTER TABLE TB_ORDERS MODIFY COLUMN EXECUTED_TIME DATETIME COMMENT '체결 시간';
ALTER TABLE TB_ORDERS MODIFY COLUMN MESSAGE VARCHAR(500) COMMENT '메시지';
ALTER TABLE TB_ORDERS MODIFY COLUMN CREATED_AT DATETIME COMMENT '생성 시간';
ALTER TABLE TB_ORDERS MODIFY COLUMN UPDATED_AT DATETIME COMMENT '수정 시간';

-- TB_TRADING_SETTINGS
ALTER TABLE TB_TRADING_SETTINGS MODIFY COLUMN TB_TRADING_SETTINGS_UID VARCHAR(36) COMMENT '설정 고유 ID (UUID)';
ALTER TABLE TB_TRADING_SETTINGS MODIFY COLUMN ACCOUNT_NO VARCHAR(20) COMMENT '계좌번호';
ALTER TABLE TB_TRADING_SETTINGS MODIFY COLUMN USER_ID VARCHAR(36) COMMENT '사용자 ID (설정 소유자)';
ALTER TABLE TB_TRADING_SETTINGS MODIFY COLUMN MAX_INVESTMENT_AMOUNT DECIMAL(18,2) COMMENT '최대 투자금액';
ALTER TABLE TB_TRADING_SETTINGS MODIFY COLUMN MIN_INVESTMENT_AMOUNT DECIMAL(18,2) COMMENT '최소 투자금액';
ALTER TABLE TB_TRADING_SETTINGS MODIFY COLUMN DEFAULT_CURRENCY VARCHAR(3) COMMENT '기본 통화 (예: KRW)';
ALTER TABLE TB_TRADING_SETTINGS MODIFY COLUMN AUTO_TRADING_ENABLED TINYINT(1) COMMENT '자동 매매 활성화 여부';
ALTER TABLE TB_TRADING_SETTINGS MODIFY COLUMN RISK_LEVEL DECIMAL(3,2) COMMENT '리스크 레벨 (0.0~1.0)';
ALTER TABLE TB_TRADING_SETTINGS MODIFY COLUMN CREATED_AT DATETIME COMMENT '생성 시간';
ALTER TABLE TB_TRADING_SETTINGS MODIFY COLUMN UPDATED_AT DATETIME COMMENT '수정 시간';

-- TB_PORTFOLIOS
ALTER TABLE TB_PORTFOLIOS MODIFY COLUMN TB_PORTFOLIOS_UID VARCHAR(36) COMMENT '포트폴리오 고유 ID (UUID)';
ALTER TABLE TB_PORTFOLIOS MODIFY COLUMN ACCOUNT_NO VARCHAR(20) COMMENT '계좌번호';
ALTER TABLE TB_PORTFOLIOS MODIFY COLUMN USER_ID VARCHAR(36) COMMENT '사용자 ID (선택, 마이그레이션용)';
ALTER TABLE TB_PORTFOLIOS MODIFY COLUMN SYMBOL VARCHAR(20) COMMENT '종목 코드';
ALTER TABLE TB_PORTFOLIOS MODIFY COLUMN NAME VARCHAR(100) COMMENT '종목명';
ALTER TABLE TB_PORTFOLIOS MODIFY COLUMN QUANTITY INT COMMENT '보유 수량';
ALTER TABLE TB_PORTFOLIOS MODIFY COLUMN AVERAGE_PRICE DECIMAL(18,2) COMMENT '평균 매수가';
ALTER TABLE TB_PORTFOLIOS MODIFY COLUMN CURRENT_PRICE DECIMAL(18,2) COMMENT '현재가';
ALTER TABLE TB_PORTFOLIOS MODIFY COLUMN CURRENCY VARCHAR(3) COMMENT '통화';
ALTER TABLE TB_PORTFOLIOS MODIFY COLUMN LAST_UPDATED DATETIME COMMENT '마지막 업데이트 시간';
ALTER TABLE TB_PORTFOLIOS MODIFY COLUMN CREATED_AT DATETIME COMMENT '생성 시간';
ALTER TABLE TB_PORTFOLIOS MODIFY COLUMN UPDATED_AT DATETIME COMMENT '수정 시간';

-- TB_STRATEGIES
ALTER TABLE TB_STRATEGIES MODIFY COLUMN TB_STRATEGIES_UID VARCHAR(36) COMMENT '전략 고유 ID (UUID)';
ALTER TABLE TB_STRATEGIES MODIFY COLUMN ACCOUNT_NO VARCHAR(20) COMMENT '계좌번호';
ALTER TABLE TB_STRATEGIES MODIFY COLUMN USER_ID VARCHAR(36) COMMENT '사용자 ID (선택, 마이그레이션용)';
ALTER TABLE TB_STRATEGIES MODIFY COLUMN STRATEGY_TYPE VARCHAR(20) COMMENT '전략 타입';
ALTER TABLE TB_STRATEGIES MODIFY COLUMN STATUS VARCHAR(20) COMMENT '전략 상태';
ALTER TABLE TB_STRATEGIES MODIFY COLUMN MAX_INVESTMENT_AMOUNT DECIMAL(18,2) COMMENT '최대 투자금액';
ALTER TABLE TB_STRATEGIES MODIFY COLUMN MIN_INVESTMENT_AMOUNT DECIMAL(18,2) COMMENT '최소 투자금액';
ALTER TABLE TB_STRATEGIES MODIFY COLUMN RISK_LEVEL DECIMAL(3,2) COMMENT '리스크 레벨';
ALTER TABLE TB_STRATEGIES MODIFY COLUMN CONFIDENCE_THRESHOLD DECIMAL(3,2) COMMENT '신뢰도 임계값';
ALTER TABLE TB_STRATEGIES MODIFY COLUMN LAST_EXECUTED_AT DATETIME COMMENT '마지막 실행 시간';
ALTER TABLE TB_STRATEGIES MODIFY COLUMN TOTAL_EXECUTIONS BIGINT COMMENT '총 실행 횟수';
ALTER TABLE TB_STRATEGIES MODIFY COLUMN SUCCESS_COUNT BIGINT COMMENT '성공 횟수';
ALTER TABLE TB_STRATEGIES MODIFY COLUMN FAILURE_COUNT BIGINT COMMENT '실패 횟수';
ALTER TABLE TB_STRATEGIES MODIFY COLUMN TOTAL_PROFIT_LOSS DECIMAL(18,2) COMMENT '총 손익';
ALTER TABLE TB_STRATEGIES MODIFY COLUMN CREATED_AT DATETIME COMMENT '생성 시간';
ALTER TABLE TB_STRATEGIES MODIFY COLUMN UPDATED_AT DATETIME COMMENT '수정 시간';

-- TB_TRADING_PORTFOLIOS
ALTER TABLE TB_TRADING_PORTFOLIOS MODIFY COLUMN TB_TRADING_PORTFOLIOS_UID VARCHAR(36) COMMENT '포트폴리오 고유 ID (UUID)';
ALTER TABLE TB_TRADING_PORTFOLIOS MODIFY COLUMN TRADING_DATE DATE COMMENT '거래일 (UNIQUE)';
ALTER TABLE TB_TRADING_PORTFOLIOS MODIFY COLUMN MARKET_SUMMARY TEXT COMMENT '시장 요약';
ALTER TABLE TB_TRADING_PORTFOLIOS MODIFY COLUMN TOP_SECTOR_1 VARCHAR(100) COMMENT '유망 섹터 1';
ALTER TABLE TB_TRADING_PORTFOLIOS MODIFY COLUMN TOP_SECTOR_2 VARCHAR(100) COMMENT '유망 섹터 2';
ALTER TABLE TB_TRADING_PORTFOLIOS MODIFY COLUMN TOP_SECTOR_3 VARCHAR(100) COMMENT '유망 섹터 3';
ALTER TABLE TB_TRADING_PORTFOLIOS MODIFY COLUMN RISK_MANAGEMENT_STRATEGY TEXT COMMENT '리스크 관리 전략';
ALTER TABLE TB_TRADING_PORTFOLIOS MODIFY COLUMN POSITION_SIZE DECIMAL(18,2) COMMENT '포지션 사이즈';
ALTER TABLE TB_TRADING_PORTFOLIOS MODIFY COLUMN CREATED_AT DATETIME COMMENT '생성 시간';
ALTER TABLE TB_TRADING_PORTFOLIOS MODIFY COLUMN UPDATED_AT DATETIME COMMENT '수정 시간';

-- TB_TRADING_PORTFOLIO_ITEMS
ALTER TABLE TB_TRADING_PORTFOLIO_ITEMS MODIFY COLUMN TB_TRADING_PORTFOLIO_ITEMS_UID VARCHAR(36) COMMENT '종목 고유 ID (UUID)';
ALTER TABLE TB_TRADING_PORTFOLIO_ITEMS MODIFY COLUMN TRADING_PORTFOLIO_ID VARCHAR(36) COMMENT '포트폴리오 ID (FK)';
ALTER TABLE TB_TRADING_PORTFOLIO_ITEMS MODIFY COLUMN SYMBOL VARCHAR(20) COMMENT '종목 코드';
ALTER TABLE TB_TRADING_PORTFOLIO_ITEMS MODIFY COLUMN NAME VARCHAR(100) COMMENT '종목명';
ALTER TABLE TB_TRADING_PORTFOLIO_ITEMS MODIFY COLUMN ENTRY_PRICE_MIN DECIMAL(18,2) COMMENT '최소 진입가';
ALTER TABLE TB_TRADING_PORTFOLIO_ITEMS MODIFY COLUMN ENTRY_PRICE_MAX DECIMAL(18,2) COMMENT '최대 진입가';
ALTER TABLE TB_TRADING_PORTFOLIO_ITEMS MODIFY COLUMN STOP_LOSS_PRICE DECIMAL(18,2) COMMENT '손절가';
ALTER TABLE TB_TRADING_PORTFOLIO_ITEMS MODIFY COLUMN TARGET_PRICE_1 DECIMAL(18,2) COMMENT '목표가 1';
ALTER TABLE TB_TRADING_PORTFOLIO_ITEMS MODIFY COLUMN TARGET_PRICE_2 DECIMAL(18,2) COMMENT '목표가 2';
ALTER TABLE TB_TRADING_PORTFOLIO_ITEMS MODIFY COLUMN EXPECTED_RETURN_RATE DECIMAL(5,2) COMMENT '기대 수익률 (%)';
ALTER TABLE TB_TRADING_PORTFOLIO_ITEMS MODIFY COLUMN RISK_REWARD_RATIO DECIMAL(5,2) COMMENT '리스크/리워드 비율';
ALTER TABLE TB_TRADING_PORTFOLIO_ITEMS MODIFY COLUMN TECHNICAL_BASIS TEXT COMMENT '기술적 근거';
ALTER TABLE TB_TRADING_PORTFOLIO_ITEMS MODIFY COLUMN SUPPLY_DEMAND_BASIS TEXT COMMENT '수급 근거';
ALTER TABLE TB_TRADING_PORTFOLIO_ITEMS MODIFY COLUMN CATALYST_FACTOR TEXT COMMENT '촉매 요인';
ALTER TABLE TB_TRADING_PORTFOLIO_ITEMS MODIFY COLUMN BUY_TIME TIME COMMENT '매수 시간';
ALTER TABLE TB_TRADING_PORTFOLIO_ITEMS MODIFY COLUMN SELL_TIME TIME COMMENT '매도 시간';
ALTER TABLE TB_TRADING_PORTFOLIO_ITEMS MODIFY COLUMN INVESTMENT_AMOUNT DECIMAL(18,2) COMMENT '투자금액';
ALTER TABLE TB_TRADING_PORTFOLIO_ITEMS MODIFY COLUMN EXPECTED_PROFIT DECIMAL(18,2) COMMENT '예상 수익';
ALTER TABLE TB_TRADING_PORTFOLIO_ITEMS MODIFY COLUMN RANKING INT COMMENT '순위';
ALTER TABLE TB_TRADING_PORTFOLIO_ITEMS MODIFY COLUMN CREATED_AT DATETIME COMMENT '생성 시간';
ALTER TABLE TB_TRADING_PORTFOLIO_ITEMS MODIFY COLUMN UPDATED_AT DATETIME COMMENT '수정 시간';
