-- Create all JPA entity tables not yet created by earlier Flyway migrations.
-- Enables ddl-auto: validate on fresh DB (e.g. local TimescaleDB). PostgreSQL/TimescaleDB compatible.

-- TB_DAILY_STOCK (composite PK: BAS_DT, SYMBOL)
CREATE TABLE IF NOT EXISTS TB_DAILY_STOCK (
    BAS_DT       DATE NOT NULL,
    SYMBOL       VARCHAR(20) NOT NULL,
    MARKET       VARCHAR(10) NOT NULL,
    OPEN_PRICE   NUMERIC(20,4),
    HIGH_PRICE   NUMERIC(20,4),
    LOW_PRICE    NUMERIC(20,4),
    CLOSE_PRICE  NUMERIC(20,4),
    VOLUME       BIGINT,
    TRD_VAL      BIGINT,
    CREATED_AT   TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (BAS_DT, SYMBOL)
);
CREATE INDEX IF NOT EXISTS IDX_TB_DAILY_STOCK_BAS_DT ON TB_DAILY_STOCK (BAS_DT);
CREATE INDEX IF NOT EXISTS IDX_TB_DAILY_STOCK_SYMBOL ON TB_DAILY_STOCK (SYMBOL);
CREATE INDEX IF NOT EXISTS IDX_TB_DAILY_STOCK_MARKET ON TB_DAILY_STOCK (MARKET);
CREATE INDEX IF NOT EXISTS IDX_TB_DAILY_STOCK_BAS_DT_SYMBOL ON TB_DAILY_STOCK (BAS_DT, SYMBOL);

-- TB_ORDER_FLOW (composite PK: BAS_DT, SYMBOL, MARKET)
CREATE TABLE IF NOT EXISTS TB_ORDER_FLOW (
    BAS_DT         DATE NOT NULL,
    SYMBOL         VARCHAR(20) NOT NULL,
    MARKET         VARCHAR(10) NOT NULL,
    NET_BUY_AMT_5D BIGINT,
    NET_BUY_AMT_1D BIGINT,
    MARKET_CAP     BIGINT,
    CREATED_AT     TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (BAS_DT, SYMBOL, MARKET)
);
CREATE INDEX IF NOT EXISTS IDX_TB_ORDER_FLOW_BAS_DT_MARKET ON TB_ORDER_FLOW (BAS_DT, MARKET);

-- TB_TRADING_SETTINGS
CREATE TABLE IF NOT EXISTS TB_TRADING_SETTINGS (
    TB_TRADING_SETTINGS_UID VARCHAR(36) NOT NULL PRIMARY KEY,
    ACCOUNT_NO              VARCHAR(20) NOT NULL,
    USER_ID                 VARCHAR(36),
    MAX_INVESTMENT_AMOUNT   NUMERIC(18,2) NOT NULL,
    MIN_INVESTMENT_AMOUNT   NUMERIC(18,2) NOT NULL,
    DEFAULT_CURRENCY        VARCHAR(3) NOT NULL,
    AUTO_TRADING_ENABLED    BOOLEAN NOT NULL DEFAULT false,
    ROBO_ADVISOR_ENABLED    BOOLEAN NOT NULL DEFAULT false,
    RISK_LEVEL              NUMERIC(3,2),
    SHORT_TERM_RATIO        NUMERIC(5,4),
    MEDIUM_TERM_RATIO       NUMERIC(5,4),
    LONG_TERM_RATIO         NUMERIC(5,4),
    CREATED_AT              TIMESTAMP(6) NOT NULL,
    UPDATED_AT              TIMESTAMP(6)
);
CREATE INDEX IF NOT EXISTS IDX_TB_TRADING_SETTINGS_USER_ID ON TB_TRADING_SETTINGS (USER_ID);
CREATE UNIQUE INDEX IF NOT EXISTS UK_TB_TRADING_SETTINGS_USER_ACCOUNT ON TB_TRADING_SETTINGS (USER_ID, ACCOUNT_NO);

-- TB_TRADING_PORTFOLIOS
CREATE TABLE IF NOT EXISTS TB_TRADING_PORTFOLIOS (
    TB_TRADING_PORTFOLIOS_UID VARCHAR(36) NOT NULL PRIMARY KEY,
    TRADING_DATE              DATE NOT NULL UNIQUE,
    MARKET_SUMMARY            TEXT,
    TOP_SECTOR_1              VARCHAR(100),
    TOP_SECTOR_2              VARCHAR(100),
    TOP_SECTOR_3              VARCHAR(100),
    RISK_MANAGEMENT_STRATEGY  TEXT,
    POSITION_SIZE             NUMERIC(18,2),
    CREATED_AT                TIMESTAMP(6) NOT NULL,
    UPDATED_AT                TIMESTAMP(6)
);

-- TB_TRADING_PORTFOLIO_ITEMS
CREATE TABLE IF NOT EXISTS TB_TRADING_PORTFOLIO_ITEMS (
    TB_TRADING_PORTFOLIO_ITEMS_UID VARCHAR(36) NOT NULL PRIMARY KEY,
    TRADING_PORTFOLIO_ID           VARCHAR(36) NOT NULL,
    SYMBOL                         VARCHAR(20) NOT NULL,
    NAME                           VARCHAR(100),
    ENTRY_PRICE_MIN                NUMERIC(18,2),
    ENTRY_PRICE_MAX                NUMERIC(18,2),
    STOP_LOSS_PRICE                NUMERIC(18,2),
    TARGET_PRICE_1                 NUMERIC(18,2),
    TARGET_PRICE_2                 NUMERIC(18,2),
    EXPECTED_RETURN_RATE           NUMERIC(5,2),
    RISK_REWARD_RATIO              NUMERIC(5,2),
    TECHNICAL_BASIS                TEXT,
    SUPPLY_DEMAND_BASIS            TEXT,
    CATALYST_FACTOR                TEXT,
    BUY_TIME                       TIME NOT NULL,
    SELL_TIME                      TIME,
    INVESTMENT_AMOUNT              NUMERIC(18,2),
    EXPECTED_PROFIT                 NUMERIC(18,2),
    RANKING                        INTEGER NOT NULL,
    CREATED_AT                     TIMESTAMP(6) NOT NULL,
    UPDATED_AT                     TIMESTAMP(6),
    CONSTRAINT FK_TB_TPI_PORTFOLIO FOREIGN KEY (TRADING_PORTFOLIO_ID) REFERENCES TB_TRADING_PORTFOLIOS(TB_TRADING_PORTFOLIOS_UID)
);

-- TB_UNIVERSE (composite PK: BAS_DT, MARKET, SYMBOL)
CREATE TABLE IF NOT EXISTS TB_UNIVERSE (
    BAS_DT     DATE NOT NULL,
    MARKET     VARCHAR(10) NOT NULL,
    SYMBOL     VARCHAR(20) NOT NULL,
    CREATED_AT TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (BAS_DT, MARKET, SYMBOL)
);
CREATE INDEX IF NOT EXISTS IDX_TB_UNIVERSE_BAS_DT ON TB_UNIVERSE (BAS_DT);
CREATE INDEX IF NOT EXISTS IDX_TB_UNIVERSE_MARKET ON TB_UNIVERSE (MARKET);
CREATE INDEX IF NOT EXISTS IDX_TB_UNIVERSE_BAS_DT_MARKET ON TB_UNIVERSE (BAS_DT, MARKET);

-- TB_USER_ACCOUNTS
CREATE TABLE IF NOT EXISTS TB_USER_ACCOUNTS (
    TB_USER_ACCOUNTS_UID VARCHAR(36) NOT NULL PRIMARY KEY,
    USER_ID              VARCHAR(36) NOT NULL,
    USER_API_KEY_ID      VARCHAR(36) NOT NULL,
    ACCOUNT_NO_ENCRYPTED TEXT NOT NULL,
    BROKER_TYPE          VARCHAR(50) NOT NULL,
    SERVER_TYPE          VARCHAR(1) NOT NULL DEFAULT '1',
    ACCOUNT_NAME         VARCHAR(100),
    IS_DEFAULT           BOOLEAN NOT NULL DEFAULT false,
    IS_ACTIVE            BOOLEAN NOT NULL DEFAULT true,
    CREATED_AT           TIMESTAMP(6) NOT NULL,
    UPDATED_AT           TIMESTAMP(6)
);
CREATE INDEX IF NOT EXISTS IDX_USER_ACCOUNTS_USER_ID ON TB_USER_ACCOUNTS (USER_ID);
CREATE INDEX IF NOT EXISTS IDX_USER_ACCOUNTS_USER_API_KEY ON TB_USER_ACCOUNTS (USER_API_KEY_ID);
CREATE INDEX IF NOT EXISTS IDX_USER_ACCOUNTS_BROKER_TYPE ON TB_USER_ACCOUNTS (BROKER_TYPE);
CREATE INDEX IF NOT EXISTS IDX_USER_ACCOUNTS_SERVER_TYPE ON TB_USER_ACCOUNTS (SERVER_TYPE);
CREATE INDEX IF NOT EXISTS IDX_USER_ACCOUNTS_IS_DEFAULT ON TB_USER_ACCOUNTS (USER_ID, SERVER_TYPE, IS_DEFAULT);
CREATE UNIQUE INDEX IF NOT EXISTS UK_USER_ACCOUNTS_USER_ACCOUNT ON TB_USER_ACCOUNTS (USER_ID, ACCOUNT_NO_ENCRYPTED, BROKER_TYPE, SERVER_TYPE);

-- TB_USER_API_KEYS
CREATE TABLE IF NOT EXISTS TB_USER_API_KEYS (
    TB_USER_API_KEYS_UID VARCHAR(36) NOT NULL PRIMARY KEY,
    USER_ID              VARCHAR(36) NOT NULL,
    BROKER_TYPE          VARCHAR(50) NOT NULL,
    APP_KEY_ENCRYPTED    TEXT NOT NULL,
    APP_SECRET_ENCRYPTED TEXT NOT NULL,
    SERVER_TYPE          VARCHAR(1) NOT NULL DEFAULT '1',
    CREATED_AT           TIMESTAMP(6) NOT NULL,
    UPDATED_AT           TIMESTAMP(6)
);
CREATE INDEX IF NOT EXISTS IDX_USER_API_KEY_USER_ID ON TB_USER_API_KEYS (USER_ID);
CREATE INDEX IF NOT EXISTS IDX_USER_API_KEY_BROKER_TYPE ON TB_USER_API_KEYS (BROKER_TYPE);

-- TB_STRATEGIES
CREATE TABLE IF NOT EXISTS TB_STRATEGIES (
    TB_STRATEGIES_UID     VARCHAR(36) NOT NULL PRIMARY KEY,
    ACCOUNT_NO            VARCHAR(20) NOT NULL,
    USER_ID               VARCHAR(36),
    MARKET                VARCHAR(10) NOT NULL,
    STRATEGY_TYPE         VARCHAR(20) NOT NULL,
    STATUS                VARCHAR(20) NOT NULL,
    MAX_INVESTMENT_AMOUNT NUMERIC(18,2),
    MIN_INVESTMENT_AMOUNT NUMERIC(18,2),
    RISK_LEVEL            NUMERIC(3,2),
    CONFIDENCE_THRESHOLD   NUMERIC(3,2),
    LAST_EXECUTED_AT      TIMESTAMP(6),
    TOTAL_EXECUTIONS      BIGINT,
    SUCCESS_COUNT         BIGINT,
    FAILURE_COUNT         BIGINT,
    TOTAL_PROFIT_LOSS     NUMERIC(18,2),
    CREATED_AT            TIMESTAMP(6) NOT NULL,
    UPDATED_AT            TIMESTAMP(6)
);
CREATE INDEX IF NOT EXISTS IDX_TB_STRATEGIES_USER_ID ON TB_STRATEGIES (USER_ID);
CREATE INDEX IF NOT EXISTS IDX_TB_STRATEGIES_MARKET ON TB_STRATEGIES (MARKET);
CREATE UNIQUE INDEX IF NOT EXISTS UK_TB_STRATEGIES_ACCOUNT_MARKET_TYPE ON TB_STRATEGIES (ACCOUNT_NO, MARKET, STRATEGY_TYPE);

-- TB_SYMBOL_SECTOR (composite PK: SYMBOL, MARKET, SECTOR_CODE)
CREATE TABLE IF NOT EXISTS TB_SYMBOL_SECTOR (
    SYMBOL      VARCHAR(20) NOT NULL,
    MARKET      VARCHAR(10) NOT NULL,
    SECTOR_CODE VARCHAR(50) NOT NULL,
    CREATED_AT  TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (SYMBOL, MARKET, SECTOR_CODE)
);
CREATE INDEX IF NOT EXISTS IDX_TB_SYMBOL_SECTOR_MARKET_SECTOR ON TB_SYMBOL_SECTOR (MARKET, SECTOR_CODE);

-- TB_SECTOR_RETURN (composite PK: BAS_DT, MARKET, SECTOR_CODE)
CREATE TABLE IF NOT EXISTS TB_SECTOR_RETURN (
    BAS_DT     DATE NOT NULL,
    MARKET     VARCHAR(10) NOT NULL,
    SECTOR_CODE VARCHAR(50) NOT NULL,
    RETURN_PCT NUMERIC(12,4),
    CREATED_AT TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (BAS_DT, MARKET, SECTOR_CODE)
);
CREATE INDEX IF NOT EXISTS IDX_TB_SECTOR_RETURN_BAS_DT_MARKET ON TB_SECTOR_RETURN (BAS_DT, MARKET);

-- TB_FUNDAMENTALS (composite PK: BAS_DT, SYMBOL, MARKET)
CREATE TABLE IF NOT EXISTS TB_FUNDAMENTALS (
    BAS_DT               DATE NOT NULL,
    SYMBOL               VARCHAR(20) NOT NULL,
    MARKET               VARCHAR(10) NOT NULL,
    PER                  NUMERIC(12,4),
    PEG                  NUMERIC(12,4),
    REVENUE_GROWTH_PCT   NUMERIC(12,4),
    OPERATING_MARGIN_PCT NUMERIC(12,4),
    CREATED_AT           TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (BAS_DT, SYMBOL, MARKET)
);
CREATE INDEX IF NOT EXISTS IDX_TB_FUNDAMENTALS_BAS_DT_MARKET ON TB_FUNDAMENTALS (BAS_DT, MARKET);

-- TB_NEWS_ITEMS
CREATE TABLE IF NOT EXISTS TB_NEWS_ITEMS (
    TB_NEWS_ITEMS_UID VARCHAR(36) NOT NULL PRIMARY KEY,
    SOURCE            VARCHAR(50) NOT NULL,
    MARKET            VARCHAR(10) NOT NULL,
    ITEM_TYPE         VARCHAR(20) NOT NULL,
    TITLE             VARCHAR(500) NOT NULL,
    SUMMARY           TEXT,
    URL               VARCHAR(1000) NOT NULL,
    COLLECTED_AT      TIMESTAMP(6) NOT NULL,
    SYMBOL            VARCHAR(20),
    SENTIMENT_SCORE   NUMERIC(5,2),
    IMPORTANCE_SCORE  NUMERIC(5,2),
    EVENT_TYPE        VARCHAR(500),
    CREATED_AT        TIMESTAMP(6) NOT NULL,
    UPDATED_AT        TIMESTAMP(6)
);
CREATE INDEX IF NOT EXISTS IDX_TB_NEWS_ITEMS_MARKET ON TB_NEWS_ITEMS (MARKET);
CREATE INDEX IF NOT EXISTS IDX_TB_NEWS_ITEMS_COLLECTED_AT ON TB_NEWS_ITEMS (COLLECTED_AT);
CREATE INDEX IF NOT EXISTS IDX_TB_NEWS_ITEMS_SYMBOL ON TB_NEWS_ITEMS (SYMBOL);

-- TB_EARNINGS_SURPRISE (composite PK: SYMBOL, MARKET, REPORT_DT)
CREATE TABLE IF NOT EXISTS TB_EARNINGS_SURPRISE (
    SYMBOL        VARCHAR(20) NOT NULL,
    MARKET        VARCHAR(10) NOT NULL,
    REPORT_DT     DATE NOT NULL,
    SURPRISE_SCORE NUMERIC(12,4),
    CREATED_AT    TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (SYMBOL, MARKET, REPORT_DT)
);
CREATE INDEX IF NOT EXISTS IDX_TB_EARNINGS_SURPRISE_MARKET_REPORT_DT ON TB_EARNINGS_SURPRISE (MARKET, REPORT_DT);

-- TB_KOREA_INVESTMENT_TOKENS
CREATE TABLE IF NOT EXISTS TB_KOREA_INVESTMENT_TOKENS (
    TB_KI_TOKENS_UID    VARCHAR(36) NOT NULL PRIMARY KEY,
    USER_ID             VARCHAR(36) NOT NULL,
    SERVER_TYPE         VARCHAR(1) NOT NULL DEFAULT '1',
    ACCESS_TOKEN_ENCRYPTED TEXT NOT NULL,
    EXPIRES_AT          BIGINT NOT NULL,
    ISSUED_AT           TIMESTAMP(6) NOT NULL,
    CREATED_AT          TIMESTAMP(6) NOT NULL,
    UPDATED_AT          TIMESTAMP(6)
);
CREATE INDEX IF NOT EXISTS IDX_KI_TOKEN_USER_ID ON TB_KOREA_INVESTMENT_TOKENS (USER_ID);
CREATE UNIQUE INDEX IF NOT EXISTS UK_KI_TOKENS_USER_SERVER ON TB_KOREA_INVESTMENT_TOKENS (USER_ID, SERVER_TYPE);

-- TB_PORTFOLIOS
CREATE TABLE IF NOT EXISTS TB_PORTFOLIOS (
    TB_PORTFOLIOS_UID VARCHAR(36) NOT NULL PRIMARY KEY,
    ACCOUNT_NO        VARCHAR(20) NOT NULL,
    USER_ID           VARCHAR(36),
    SYMBOL            VARCHAR(20) NOT NULL,
    NAME              VARCHAR(100),
    QUANTITY          INTEGER NOT NULL,
    AVERAGE_PRICE     NUMERIC(18,2) NOT NULL,
    CURRENT_PRICE     NUMERIC(18,2),
    CURRENCY          VARCHAR(3) NOT NULL,
    LAST_UPDATED      TIMESTAMP(6),
    CREATED_AT        TIMESTAMP(6) NOT NULL,
    UPDATED_AT        TIMESTAMP(6)
);
CREATE INDEX IF NOT EXISTS IDX_TB_PORTFOLIOS_USER_ID ON TB_PORTFOLIOS (USER_ID);

-- TB_SIGNAL_SCORE (composite PK: BAS_DT, SYMBOL, FACTOR_TYPE)
CREATE TABLE IF NOT EXISTS TB_SIGNAL_SCORE (
    BAS_DT     DATE NOT NULL,
    SYMBOL     VARCHAR(20) NOT NULL,
    FACTOR_TYPE VARCHAR(50) NOT NULL,
    MARKET     VARCHAR(10) NOT NULL,
    SCORE      NUMERIC(20,6),
    METADATA   VARCHAR(500),
    CREATED_AT TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (BAS_DT, SYMBOL, FACTOR_TYPE)
);
CREATE INDEX IF NOT EXISTS IDX_TB_SIGNAL_SCORE_BAS_DT ON TB_SIGNAL_SCORE (BAS_DT);
CREATE INDEX IF NOT EXISTS IDX_TB_SIGNAL_SCORE_SYMBOL ON TB_SIGNAL_SCORE (SYMBOL);
CREATE INDEX IF NOT EXISTS IDX_TB_SIGNAL_SCORE_MARKET ON TB_SIGNAL_SCORE (MARKET);
CREATE INDEX IF NOT EXISTS IDX_TB_SIGNAL_SCORE_FACTOR_TYPE ON TB_SIGNAL_SCORE (FACTOR_TYPE);
CREATE INDEX IF NOT EXISTS IDX_TB_SIGNAL_SCORE_BAS_DT_MARKET ON TB_SIGNAL_SCORE (BAS_DT, MARKET);
