-- 계정별 파이프라인 실행 플래그. NULL = 서버 기본값 사용, NOT NULL = 사용자 선택값.
ALTER TABLE TB_TRADING_SETTINGS ADD COLUMN IF NOT EXISTS PIPELINE_AUTO_EXECUTE BOOLEAN NULL;
ALTER TABLE TB_TRADING_SETTINGS ADD COLUMN IF NOT EXISTS PIPELINE_ALLOW_REAL_EXECUTION BOOLEAN NULL;

COMMENT ON COLUMN TB_TRADING_SETTINGS.PIPELINE_AUTO_EXECUTE IS '파이프라인 자동 실행 허용. NULL=서버 기본값';
COMMENT ON COLUMN TB_TRADING_SETTINGS.PIPELINE_ALLOW_REAL_EXECUTION IS '실계좌 자동 실행 허용. NULL=서버 기본값';
