-- 서버 전역(시스템) 기본값. 관리자가 Ops 화면에서 조회·수정. 계정별 설정(TB_TRADING_SETTINGS)과 별개.
CREATE TABLE IF NOT EXISTS TB_SYSTEM_SETTINGS (
    KEY VARCHAR(100) NOT NULL PRIMARY KEY,
    VALUE TEXT,
    DESCRIPTION VARCHAR(500),
    UPDATED_AT TIMESTAMP(6),
    UPDATED_BY VARCHAR(36)
);

COMMENT ON TABLE TB_SYSTEM_SETTINGS IS '서버 전역 설정(키-값). DB 값 우선, 없으면 application.yml fallback';
COMMENT ON COLUMN TB_SYSTEM_SETTINGS.KEY IS '설정 키 (예: pipeline.autoExecute)';
COMMENT ON COLUMN TB_SYSTEM_SETTINGS.VALUE IS '문자열 값 (Boolean/숫자 파싱은 서비스 레이어)';
COMMENT ON COLUMN TB_SYSTEM_SETTINGS.DESCRIPTION IS '관리자 화면 표시용 설명';
COMMENT ON COLUMN TB_SYSTEM_SETTINGS.UPDATED_BY IS '최종 수정자 USER_ID';
