-- V3: TB_STRATEGIES에 MARKET 컬럼 추가, UK 변경, TB_NEWS_ITEMS 테이블 생성
-- 적용 전 DB 백업 권장. 롤백은 db/migration/rollback/V3_rollback.sql 참고.

-- 1. TB_STRATEGIES: 기존 UK 제거 후 MARKET 컬럼 추가 및 새 UK 생성
-- (MariaDB/MySQL: UK 이름이 다를 수 있으므로 실제 스키마 확인 후 실행)

ALTER TABLE TB_STRATEGIES ADD COLUMN MARKET VARCHAR(10) NOT NULL DEFAULT 'KR' COMMENT '시장 (KR, US)' AFTER USER_ID;

-- 기존 UNIQUE 제약 제거 (존재 시)
-- ALTER TABLE TB_STRATEGIES DROP INDEX UK_TB_STRATEGIES_ACCOUNT_TYPE;
-- ALTER TABLE TB_STRATEGIES DROP INDEX UK_TB_STRATEGIES_USER_ACCOUNT_TYPE;

-- 새 UNIQUE 제약 추가
ALTER TABLE TB_STRATEGIES ADD UNIQUE INDEX UK_TB_STRATEGIES_ACCOUNT_MARKET_TYPE (ACCOUNT_NO, MARKET, STRATEGY_TYPE);
ALTER TABLE TB_STRATEGIES ADD INDEX IDX_TB_STRATEGIES_MARKET (MARKET);

-- 2. TB_NEWS_ITEMS 테이블 생성
CREATE TABLE IF NOT EXISTS TB_NEWS_ITEMS (
    TB_NEWS_ITEMS_UID VARCHAR(36) NOT NULL COMMENT '고유 ID (UUID)',
    SOURCE VARCHAR(50) NOT NULL COMMENT '원천 코드',
    MARKET VARCHAR(10) NOT NULL COMMENT '시장 (KR, US)',
    ITEM_TYPE VARCHAR(20) NOT NULL COMMENT '유형 (FACT, SPEED, BUZZ)',
    TITLE VARCHAR(500) NOT NULL COMMENT '제목',
    SUMMARY TEXT NULL COMMENT '요약',
    URL VARCHAR(1000) NOT NULL COMMENT '원문 URL',
    COLLECTED_AT DATETIME NOT NULL COMMENT '수집 시각',
    SYMBOL VARCHAR(20) NULL COMMENT '연관 종목 코드',
    SENTIMENT_SCORE DECIMAL(5,2) NULL COMMENT '감정 점수',
    IMPORTANCE_SCORE DECIMAL(5,2) NULL COMMENT '중요도 점수',
    EVENT_TYPE VARCHAR(50) NULL COMMENT '이벤트 유형',
    CREATED_AT DATETIME NOT NULL COMMENT '생성 시간',
    UPDATED_AT DATETIME NULL COMMENT '수정 시간',
    PRIMARY KEY (TB_NEWS_ITEMS_UID),
    INDEX IDX_TB_NEWS_ITEMS_MARKET (MARKET),
    INDEX IDX_TB_NEWS_ITEMS_COLLECTED_AT (COLLECTED_AT),
    INDEX IDX_TB_NEWS_ITEMS_SYMBOL (SYMBOL),
    INDEX IDX_TB_NEWS_ITEMS_SOURCE_URL (SOURCE, URL(255))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='뉴스·공시 수집 항목';
