-- V4: KRX 일별 시세 저장용 TB_DAILY_STOCK 테이블 생성
-- 적용 전 DB 백업 권장. 롤백: db/migration/rollback/V4_rollback.sql 참고.

CREATE TABLE IF NOT EXISTS TB_DAILY_STOCK (
    BAS_DT DATE NOT NULL COMMENT '기준일자',
    SYMBOL VARCHAR(20) NOT NULL COMMENT '종목코드(6자리 등)',
    MARKET VARCHAR(10) NOT NULL DEFAULT 'KR' COMMENT '시장 (KR, US)',
    OPEN_PRICE DECIMAL(20,4) NULL COMMENT '시가',
    HIGH_PRICE DECIMAL(20,4) NULL COMMENT '고가',
    LOW_PRICE DECIMAL(20,4) NULL COMMENT '저가',
    CLOSE_PRICE DECIMAL(20,4) NULL COMMENT '종가',
    VOLUME BIGINT NULL COMMENT '거래량',
    TRD_VAL BIGINT NULL COMMENT '거래대금',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 시간',
    PRIMARY KEY (BAS_DT, SYMBOL),
    INDEX IDX_TB_DAILY_STOCK_BAS_DT (BAS_DT),
    INDEX IDX_TB_DAILY_STOCK_SYMBOL (SYMBOL),
    INDEX IDX_TB_DAILY_STOCK_MARKET (MARKET),
    INDEX IDX_TB_DAILY_STOCK_BAS_DT_SYMBOL (BAS_DT, SYMBOL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='KRX 일별 시세';
