-- V5: 시그널/팩터 점수 저장용 TB_SIGNAL_SCORE 테이블 생성
-- 적용 전 DB 백업 권장. 롤백: db/migration/rollback/V5_rollback.sql 참고.

CREATE TABLE IF NOT EXISTS TB_SIGNAL_SCORE (
    BAS_DT DATE NOT NULL COMMENT '기준일자',
    SYMBOL VARCHAR(20) NOT NULL COMMENT '종목코드',
    MARKET VARCHAR(10) NOT NULL DEFAULT 'KR' COMMENT '시장 (KR, US)',
    FACTOR_TYPE VARCHAR(50) NOT NULL COMMENT '팩터/시그널 유형 (DISPARITY, VOLATILITY_BREAKOUT, LIQUIDITY 등)',
    SCORE DECIMAL(20,6) NULL COMMENT '점수',
    METADATA VARCHAR(500) NULL COMMENT '메타데이터(JSON 등)',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 시간',
    PRIMARY KEY (BAS_DT, SYMBOL, FACTOR_TYPE),
    INDEX IDX_TB_SIGNAL_SCORE_BAS_DT (BAS_DT),
    INDEX IDX_TB_SIGNAL_SCORE_SYMBOL (SYMBOL),
    INDEX IDX_TB_SIGNAL_SCORE_MARKET (MARKET),
    INDEX IDX_TB_SIGNAL_SCORE_FACTOR_TYPE (FACTOR_TYPE),
    INDEX IDX_TB_SIGNAL_SCORE_BAS_DT_MARKET (BAS_DT, MARKET)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='시그널/팩터 점수';
