-- V6: 유니버스(감시 대상 종목) 저장용 TB_UNIVERSE 테이블 생성
-- 적용 전 DB 백업 권장. 롤백: db/migration/rollback/V6_rollback.sql 참고.

CREATE TABLE IF NOT EXISTS TB_UNIVERSE (
    BAS_DT DATE NOT NULL COMMENT '기준일자',
    MARKET VARCHAR(10) NOT NULL DEFAULT 'KR' COMMENT '시장 (KR, US)',
    SYMBOL VARCHAR(20) NOT NULL COMMENT '종목코드',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 시간',
    PRIMARY KEY (BAS_DT, MARKET, SYMBOL),
    INDEX IDX_TB_UNIVERSE_BAS_DT (BAS_DT),
    INDEX IDX_TB_UNIVERSE_MARKET (MARKET),
    INDEX IDX_TB_UNIVERSE_BAS_DT_MARKET (BAS_DT, MARKET)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='유니버스(감시 대상 종목)';
