-- V7: 파이프라인 매수 포지션 추적용 TB_STRATEGY_POSITION 테이블 생성
-- 적용 전 DB 백업 권장. 롤백: db/migration/rollback/V7_rollback.sql 참고.

CREATE TABLE IF NOT EXISTS TB_STRATEGY_POSITION (
    ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'PK',
    ACCOUNT_NO VARCHAR(20) NOT NULL COMMENT '계좌번호',
    SYMBOL VARCHAR(20) NOT NULL COMMENT '종목코드',
    MARKET VARCHAR(10) NOT NULL DEFAULT 'KR' COMMENT '시장 (KR, US)',
    ENTRY_DT DATE NOT NULL COMMENT '진입일',
    ENTRY_PRICE DECIMAL(20,4) NOT NULL COMMENT '진입가',
    QUANTITY INT NOT NULL COMMENT '수량',
    TRAILING_HIGH DECIMAL(20,4) NULL COMMENT '추적 고가(ATR Trailing Stop용)',
    ATR_MULTIPLIER DECIMAL(10,4) NOT NULL DEFAULT 2.0 COMMENT 'ATR 배수',
    TIME_CUT_DAYS INT NOT NULL DEFAULT 5 COMMENT '시간 청산 일수',
    TARGET_RETURN_PCT DECIMAL(10,4) NULL COMMENT '목표 수익률(%)',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 시간',
    EXIT_DT DATE NULL COMMENT '청산일 (NULL이면 보유중)',
    EXIT_PRICE DECIMAL(20,4) NULL COMMENT '청산가',
    PRIMARY KEY (ID),
    INDEX IDX_TB_STRATEGY_POSITION_ACCOUNT (ACCOUNT_NO),
    INDEX IDX_TB_STRATEGY_POSITION_SYMBOL (SYMBOL),
    INDEX IDX_TB_STRATEGY_POSITION_OPEN (ACCOUNT_NO, EXIT_DT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='파이프라인 매수 포지션(청산 규칙 추적)';
