-- V8: TB_STRATEGY_POSITION에 STRATEGY_TYPE 컬럼 추가 (기간별 청산 규칙 분기용)
-- 적용 전 DB 백업 권장. 롤백: db/migration/rollback/V8_rollback.sql 참고.

ALTER TABLE TB_STRATEGY_POSITION
    ADD COLUMN STRATEGY_TYPE VARCHAR(20) NOT NULL DEFAULT 'SHORT_TERM' COMMENT '전략 타입 (SHORT_TERM, MEDIUM_TERM, LONG_TERM)' AFTER MARKET;

CREATE INDEX IDX_TB_STRATEGY_POSITION_ACCOUNT_EXIT_TYPE ON TB_STRATEGY_POSITION (ACCOUNT_NO, EXIT_DT, STRATEGY_TYPE);
